import Vue from 'vue'
import Vuex from 'vuex'
import bet from 'cssbeautify'

Vue.use(Vuex)

const state = {
  styles: [],
}

const mutations = {
  CREATE_STYLE(state, action) {
    state.styles.push({
      name: action.name,
      content: action.style,
    })
  },
  CLEAR_STYLES(state) {
    state = {
      styles: [],
    }
  },
}

const actions = {
  CREATE_STYLE(store, payload) {
    store.commit('CREATE_STYLE', payload)
  },
}

const getters = {
  fullStyle: state =>
    bet(
      `/* Generated by Coffeebreak v0.2 */ 
${state.styles.map(style => `.${style.name} {${style.content}}`)}`,
      {
        indent: '  ',
      }
    ),
}

export default new Vuex.Store({
  state,
  mutations,
  actions,
  getters,
})
