<template>
  <div>
    <h2>{{ head }}</h2>
    <button v-on:click="getAll">Load again</button>
    <button v-on:click="clearLocalStorage">Clear all CSS rules</button>
    <button v-on:click="createDownloadButton">Download as file</button>
    <textarea class="_full" v-model="full"></textarea>
    <div id="download"></div>
  </div>
</template>

<script>
  export default {
    name: 'Get',
    data () {
      return {
        head: 'Get your style',
        full: '/* Your style, generated by Coffeebreak */'
      }
    },
    ready () {
      this.getAll()
    },
    methods: {
      clearLocalStorage () {
        window.localStorage.clear()
      },
      createDownloadButton () {
        let a = document.createElement('a')
        a.style = 'display: none'
        let data = new window.Blob([this.full], {type: 'text/css'})
        let url = window.URL.createObjectURL(data)
        a.href = url
        a.download = 'style-' + Math.random().toString(36).slice(2)
        document.getElementById('download').appendChild(a)
        a.click()
        setTimeout(function () {
          document.getElementById('download').removeChild(a)
          window.URL.revokeObjectURL(url)
        }, 100)
      },
      getAll () {
        this.full = '/* Your style, generated by Coffeebreak */'
        for (let i = 0; i < window.localStorage.length; i++) {
          let key = window.localStorage.key(i)
          let value = window.localStorage[key]
          this.full += '\n\n.' + key + ' {\n' + value + '\n}'
        }
      }
    }
  }
</script>

<style>
  ._full {
    width: 580px !important;
    height: 350px;
  }
</style>
